const quotes = [
  "Before long, I'll have my own channel - I'll be like Barney",
  "Getting in shape for this role, which is incredibly demanding, vocally, has been a lot of hard work, but I'm nailing it. I'm even kind of, at times, blowing my own mind, because I am even able to talk right now.",
  "I did, I'd say, at least about 80 percent of the rest of the driving, and I had the time of my life.",
  "I started training for musicals since I was a boy.",
  "I wanted to play around with the format, really tear it to pieces and shake it up. For example, if Mitch saves someone from drowning, and that person then goes out and releases a virus that kills a million people. Imagine the moral implications of that.",
  "I'm six foot four, an all-American guy, and handsome and talented as well!",
  "Image is what people perceive my life to be. It's nothing like the truth.",
  "In case you haven't caught the commercials, I'm in the new SpongeBob SquarePants Movie.",
  "My one ambition was to go to Broadway, and I never gave up on that dream.",
  "My web site is so fresh. The paint is still wet, but stay tuned, because I have lots of personal things, specifically about what is happening day-to-day, that I will keep updating daily.",
  "My wife is the dancer, but I certainly know how to sing.",
  "The talent that I was blessed with was really for the theater.",
  "There are many dying children out there whose last wish is to meet me.",
  "I try to let the ladies gravitate towards me so it doesn't look like I'm trying to jump into bed with them.",
  "You won't see me in Spandex because it reveals too much of The Hoff.",
  "I've done everything, and I talk about what I`ve learnt through all those journeys: how I tried to save the world and I forgot to save myself.",
  "I believe the camera photographs your aura, and it also photographs your heart. And I cast 'Baywatch' that way.",
  "I'm recording a new romantic songs CD and for US television network PBS, we will shoot a special in the castles of Ireland, with the Celtic women dancing in unison with me.",
  "I find it a bit sad that there is no photo of me hanging on the walls in the Berlin Museum at Checkpoint Charlie.",
  "I went in and said, \"If I see one more gratuitous shot of a woman's body, I'm quitting . . . \" I think the show should be emotional story lines, morals, real- life heroes. And that's what we're doing.",
  "I've got taste.  It's inbred in me.",
  "I can do some really spiritual stuff about people that are close to me ... you know when they get in trouble with eating or alcohol or whatever comes into your life that you need to address.",
  "Beyond its entertainment value, Baywatch has enriched and, in many cases, helped save lives. I'm looking forward to the opportunity to continue with a project which has had such a significance for so many.",
  "Despite that I have been going through a painful divorce and I have recently been separated from my children due to my work, I have been successfully dealing with my issues. Unfortunately, one evening I did have a brief relapse, but part of recovery is relapse. Because of my honest and positive relationship with my daughters, who were concerned for my well being, there was a tape made that night to show me what I was like. I have seen the tape. I have learned from it and I am back on my game.",
  "I never fancied Pamela - until recently. I was sitting next to her at a party at the Playboy Mansion and there was loads of chemistry. I though how funny it would be if we hooked up.",
  "You know, I've had an interesting career. I've made a living, talking to a car, running in slow motion with Pamela Anderson, and starring with a sponge. Now, people might say there's no depth to that, but...uh...and they're right... however, it seems to have worked.",
  "I feel like Elvis. Only alive.",
  "The car was a blast. SpongeBob SquarePants was fun, but he didn't come to the set. He was a stuck-up sponge.",
  "I let people down easy with inspiration.",
  "I got a new show where we will never tell you what's coming around the corner.",
  "I would consider (a career in politics). My first law would be 'Respect', then 'Get on with your neighbours'",
  "We made sure nobody died on the show. We made sure nobody ever drowned on Baywatch.",
  "I look good, but I probably have the insides of Elvis.",
  "I'm delighted to be such a hit on the web and to be crowned king of the internet.",
  "I try to let the ladies gravitate towards me so it doesn't look like I'm trying to jump into bed with them."
]

module.exports = quotes;

